---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

## Assignment 4 - Understanding and Predicting Property Maintenance Fines

This assignment is based on a data challenge from the Michigan Data Science Team ([MDST](http://midas.umich.edu/mdst/)). 

The Michigan Data Science Team ([MDST](http://midas.umich.edu/mdst/)) and the Michigan Student Symposium for Interdisciplinary Statistical Sciences ([MSSISS](https://sites.lsa.umich.edu/mssiss/)) have partnered with the City of Detroit to help solve one of the most pressing problems facing Detroit - blight. [Blight violations](http://www.detroitmi.gov/How-Do-I/Report/Blight-Complaint-FAQs) are issued by the city to individuals who allow their properties to remain in a deteriorated condition. Every year, the city of Detroit issues millions of dollars in fines to residents and every year, many of these fines remain unpaid. Enforcing unpaid blight fines is a costly and tedious process, so the city wants to know: how can we increase blight ticket compliance?

The first step in answering this question is understanding when and why a resident might fail to comply with a blight ticket. This is where predictive modeling comes in. For this assignment, your task is to predict whether a given blight ticket will be paid on time.

All data for this assignment has been provided to us through the [Detroit Open Data Portal](https://data.detroitmi.gov/). **Only the data already included in your Coursera directory can be used for training the model for this assignment.** Nonetheless, we encourage you to look into data from other Detroit datasets to help inform feature creation and model selection. We recommend taking a look at the following related datasets:

* [Building Permits](https://data.detroitmi.gov/Property-Parcels/Building-Permits/xw2a-a7tf)
* [Trades Permits](https://data.detroitmi.gov/Property-Parcels/Trades-Permits/635b-dsgv)
* [Improve Detroit: Submitted Issues](https://data.detroitmi.gov/Government/Improve-Detroit-Submitted-Issues/fwz3-w3yn)
* [DPD: Citizen Complaints](https://data.detroitmi.gov/Public-Safety/DPD-Citizen-Complaints-2016/kahe-efs3)
* [Parcel Map](https://data.detroitmi.gov/Property-Parcels/Parcel-Map/fxkw-udwf)

___

We provide you with two data files for use in training and validating your models: train.csv and test.csv. Each row in these two files corresponds to a single blight ticket, and includes information about when, why, and to whom each ticket was issued. The target variable is compliance, which is True if the ticket was paid early, on time, or within one month of the hearing data, False if the ticket was paid after the hearing date or not at all, and Null if the violator was found not responsible. Compliance, as well as a handful of other variables that will not be available at test-time, are only included in train.csv.

Note: All tickets where the violators were found not responsible are not considered during evaluation. They are included in the training set as an additional source of data for visualization, and to enable unsupervised and semi-supervised approaches. However, they are not included in the test set.

<br>

**File descriptions** (Use only this data for training your model!)

    train.csv - the training set (all tickets issued 2004-2011)
    test.csv - the test set (all tickets issued 2012-2016)
    addresses.csv & latlons.csv - mapping from ticket id to addresses, and from addresses to lat/lon coordinates. 
     Note: misspelled addresses may be incorrectly geolocated.

<br>

**Data fields**

train.csv & test.csv

    ticket_id - unique identifier for tickets
    agency_name - Agency that issued the ticket
    inspector_name - Name of inspector that issued the ticket
    violator_name - Name of the person/organization that the ticket was issued to
    violation_street_number, violation_street_name, violation_zip_code - Address where the violation occurred
    mailing_address_str_number, mailing_address_str_name, city, state, zip_code, non_us_str_code, country - Mailing address of the violator
    ticket_issued_date - Date and time the ticket was issued
    hearing_date - Date and time the violator's hearing was scheduled
    violation_code, violation_description - Type of violation
    disposition - Judgment and judgement type
    fine_amount - Violation fine amount, excluding fees
    admin_fee - $20 fee assigned to responsible judgments
state_fee - $10 fee assigned to responsible judgments
    late_fee - 10% fee assigned to responsible judgments
    discount_amount - discount applied, if any
    clean_up_cost - DPW clean-up or graffiti removal cost
    judgment_amount - Sum of all fines and fees
    grafitti_status - Flag for graffiti violations
    
train.csv only

    payment_amount - Amount paid, if any
    payment_date - Date payment was made, if it was received
    payment_status - Current payment status as of Feb 1 2017
    balance_due - Fines and fees still owed
    collection_status - Flag for payments in collections
    compliance [target variable for prediction] 
     Null = Not responsible
     0 = Responsible, non-compliant
     1 = Responsible, compliant
    compliance_detail - More information on why each ticket was marked compliant or non-compliant


___

## Evaluation

Your predictions will be given as the probability that the corresponding blight ticket will be paid on time.

The evaluation metric for this assignment is the Area Under the ROC Curve (AUC). 

Your grade will be based on the AUC score computed for your classifier. A model which with an AUROC of 0.7 passes this assignment, over 0.75 will recieve full points.
___

For this assignment, create a function that trains a model to predict blight ticket compliance in Detroit using `train.csv`. Using this model, return a series of length 61001 with the data being the probability that each corresponding ticket from `test.csv` will be paid, and the index being the ticket_id.

Example:

    ticket_id
       284932    0.531842
       285362    0.401958
       285361    0.105928
       285338    0.018572
                 ...
       376499    0.208567
       376500    0.818759
       369851    0.018528
       Name: compliance, dtype: float32
       
### Hints

* Make sure your code is working before submitting it to the autograder.

* Print out your result to see whether there is anything weird (e.g., all probabilities are the same).

* Generally the total runtime should be less than 10 mins. You should NOT use Neural Network related classifiers (e.g., MLPClassifier) in this question. 

* Try to avoid global variables. If you have other functions besides blight_model, you should move those functions inside the scope of blight_model.

* Refer to the pinned threads in Week 4's discussion forum when there is something you could not figure it out.

In [1]:
import pandas as pd
import numpy as np

def blight_model():
    
    # Your code here
    
    return # Your answer here

In [2]:
blight_model()

In [1]:
import pandas as pd
import numpy as np

In [2]:
train=pd.read_csv('train.csv',encoding='latin-1')
test=pd.read_csv('test.csv')
add=pd.read_csv('addresses.csv')
ll=pd.read_csv('latlons.csv')

/opt/conda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (11,12,31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
train=pd.merge(train,add,how='left',on='ticket_id')
train=pd.merge(train,ll,how='left',on='address')

test=pd.merge(test,add,how='left',on='ticket_id')
test=pd.merge(test,ll,how='left',on='address')

In [5]:
test.head()

ticket_id                 agency_name      inspector_name  \
0     284932  Department of Public Works  Granberry, Aisha B   
1     285362  Department of Public Works      Lusk, Gertrina   
2     285361  Department of Public Works      Lusk, Gertrina   
3     285338  Department of Public Works   Talbert, Reginald   
4     285346  Department of Public Works   Talbert, Reginald   

        violator_name  violation_street_number violation_street_name  \
0    FLUELLEN, JOHN A                  10041.0             ROSEBERRY   
1     WHIGHAM, THELMA                  18520.0             EVERGREEN   
2     WHIGHAM, THELMA                  18520.0             EVERGREEN   
3  HARABEDIEN, POPKIN                   1835.0               CENTRAL   
4    CORBELL, STANLEY                   1700.0               CENTRAL   

  violation_zip_code mailing_address_str_number mailing_address_str_name  \
0                NaN                        141                ROSEBERRY   
1                NaN                      19136              GLASTONBURY   
2                NaN                      19136              GLASTONBURY   
3                NaN                       2246                   NELSON   
4                NaN                       3435                   MUNGER   

        city    ...     admin_fee state_fee  late_fee discount_amount  \
0    DETROIT    ...          20.0      10.0      20.0             0.0   
1    DETROIT    ...          20.0      10.0     100.0             0.0   
2    DETROIT    ...          20.0      10.0      10.0             0.0   
3  WOODHAVEN    ...          20.0      10.0      20.0             0.0   
4    LIVONIA    ...          20.0      10.0      10.0             0.0   

  clean_up_cost judgment_amount grafitti_status                      address  \
0           0.0           250.0             NaN  10041 roseberry, Detroit MI   
1           0.0          1130.0             NaN  18520 evergreen, Detroit MI   
2           0.0           140.0             NaN  18520 evergreen, Detroit MI   
3           0.0           250.0             NaN     1835 central, Detroit MI   
4           0.0           140.0             NaN     1700 central, Detroit MI   

         lat        lon  
0  42.407581 -82.986642  
1  42.426239 -83.238259  
2  42.426239 -83.238259  
3  42.309661 -83.122426  
4  42.308830 -83.121116  

[5 rows x 30 columns]

In [6]:
train.shape

(250306, 37)

In [7]:
train.dtypes
#train.info()

ticket_id                       int64
agency_name                    object
inspector_name                 object
violator_name                  object
violation_street_number       float64
violation_street_name          object
violation_zip_code            float64
mailing_address_str_number    float64
mailing_address_str_name       object
city                           object
state                          object
zip_code                       object
non_us_str_code                object
country                        object
ticket_issued_date             object
hearing_date                   object
violation_code                 object
violation_description          object
disposition                    object
fine_amount                   float64
admin_fee                     float64
state_fee                     float64
late_fee                      float64
discount_amount               float64
clean_up_cost                 float64
judgment_amount               float64
payment_amou

In [8]:
train[['fine_amount','admin_fee','state_fee','late_fee','discount_amount','clean_up_cost','judgment_amount']].head(10)

fine_amount  admin_fee  state_fee  late_fee  discount_amount  \
0        250.0       20.0       10.0      25.0              0.0   
1        750.0       20.0       10.0      75.0              0.0   
2        250.0        0.0        0.0       0.0              0.0   
3        250.0        0.0        0.0       0.0              0.0   
4        250.0        0.0        0.0       0.0              0.0   
5        250.0       20.0       10.0      25.0              0.0   
6        750.0       20.0       10.0      75.0              0.0   
7        100.0       20.0       10.0      10.0              0.0   
8        100.0       20.0       10.0      10.0              0.0   
9        750.0       20.0       10.0      75.0              0.0   

   clean_up_cost  judgment_amount  
0            0.0            305.0  
1            0.0            855.0  
2            0.0              0.0  
3            0.0              0.0  
4            0.0              0.0  
5            0.0            305.0  
6            0.0            855.0  
7            0.0            140.0  
8            0.0            140.0  
9            0.0            855.0

In [9]:
print(train['admin_fee'].nunique())
train['admin_fee'].unique()

2


array([ 20.,   0.])

In [10]:
print(train['state_fee'].nunique())
train['state_fee'].unique()

2


array([ 10.,   0.])

In [11]:
print(train['discount_amount'].nunique())
train['discount_amount'].unique()

13


array([   0.,   25.,   30.,   10.,   50.,   20.,    5.,    3.,  100.,
        250.,  350.,   13.,   40.])

In [12]:
print(train['fine_amount'].nunique())
train['fine_amount'].unique()

43


array([  2.50000000e+02,   7.50000000e+02,   1.00000000e+02,
         3.50000000e+03,   2.00000000e+02,   2.50000000e+01,
         1.00000000e+03,   3.00000000e+02,   2.00000000e+01,
         2.50000000e+03,   1.00000000e+04,   5.00000000e+02,
         5.00000000e+01,   1.50000000e+03,   5.00000000e+03,
         1.25000000e+02,   3.50000000e+02,   1.47000000e+03,
         6.00000000e+02,   3.00000000e+03,   4.00000000e+02,
         1.70000000e+02,   1.25000000e+03,   1.75000000e+03,
         1.20000000e+03,   2.00000000e+03,   9.70000000e+02,
         7.00000000e+03,              nan,   1.50000000e+02,
         2.69500000e+03,   8.00000000e+03,   9.50000000e+01,
         3.45000000e+02,   2.70000000e+02,   0.00000000e+00,
         4.50000000e+02,   1.60000000e+02,   6.55000000e+02,
         2.20000000e+02,   3.75000000e+02,   1.03000000e+03,
         6.77000000e+02,   1.00000000e+00])

In [13]:
print(train['clean_up_cost'].nunique())
train['clean_up_cost'].unique()

1


array([ 0.])

In [14]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [15]:
#sns.lmplot(x='lat',y='lon',data=train,hue='compliance',fit_reg=False)

In [16]:
## check null values in the training dataset
train.apply(lambda x:sum(x.isnull()),axis=0)

ticket_id                          0
agency_name                        0
inspector_name                     0
violator_name                     34
violation_street_number            0
violation_street_name              0
violation_zip_code            250306
mailing_address_str_number      3602
mailing_address_str_name           4
city                               0
state                             93
zip_code                           1
non_us_str_code               250303
country                            0
ticket_issued_date                 0
hearing_date                   12491
violation_code                     0
violation_description              0
disposition                        0
fine_amount                        1
admin_fee                          0
state_fee                          0
late_fee                           0
discount_amount                    0
clean_up_cost                      0
judgment_amount                    0
payment_amount                     0
b

In [17]:
# remove the null values in the training dataset, and also NaN in compliance data
train=train[~train['compliance'].isnull()]
train=train[~train['lat'].isnull()]
train=train[~train['lon'].isnull()]

In [18]:
train.shape

(159878, 37)

In [19]:
train=train[['agency_name', 'inspector_name','violation_code','disposition', 
             'fine_amount','discount_amount','lat', 'lon', 'compliance']]

In [20]:
## check null values in the training dataset
train.apply(lambda x:sum(x.isnull()),axis=0)

agency_name        0
inspector_name     0
violation_code     0
disposition        0
fine_amount        0
discount_amount    0
lat                0
lon                0
compliance         0
dtype: int64

In [21]:
train.columns

Index(['agency_name', 'inspector_name', 'violation_code', 'disposition',
       'fine_amount', 'discount_amount', 'lat', 'lon', 'compliance'],
      dtype='object')

In [22]:
train.head()

agency_name    inspector_name  \
0  Buildings, Safety Engineering & Env Department   Sims, Martinzie   
1  Buildings, Safety Engineering & Env Department  Williams, Darrin   
5  Buildings, Safety Engineering & Env Department   Sims, Martinzie   
6  Buildings, Safety Engineering & Env Department  Williams, Darrin   
7  Buildings, Safety Engineering & Env Department  Williams, Darrin   

  violation_code                   disposition  fine_amount  discount_amount  \
0      9-1-36(a)        Responsible by Default        250.0              0.0   
1     61-63.0600  Responsible by Determination        750.0              0.0   
5      9-1-36(a)        Responsible by Default        250.0              0.0   
6     61-63.0500        Responsible by Default        750.0              0.0   
7     61-63.0100        Responsible by Default        100.0              0.0   

         lat        lon  compliance  
0  42.390729 -83.124268         0.0  
1  42.326937 -83.135118         1.0  
5  42.145257 -83.208233         0.0  
6  42.433466 -83.023493         0.0  
7  42.388641 -83.037858         0.0

In [23]:
train.dtypes

agency_name         object
inspector_name      object
violation_code      object
disposition         object
fine_amount        float64
discount_amount    float64
lat                float64
lon                float64
compliance         float64
dtype: object

In [24]:
train['compliance']=train['compliance'].apply(lambda x:True if x==1 else False)

In [25]:
#sns.countplot(x='compliance',hue='agency_name',data=train)

In [26]:
#sns.countplot(x='compliance',hue='discount_amount',data=train)

In [27]:
#sns.countplot(x='compliance',hue='disposition',data=train)

In [28]:
print(train['violation_code'].nunique())
#train['violation_code'].unique()

189


In [29]:
print(train['inspector_name'].nunique())
#train['inspector_name'].unique()

159


In [30]:
#sns.pairplot(train)

In [31]:
from sklearn.preprocessing import minmax_scale,LabelEncoder

In [32]:
agn_nm_le=LabelEncoder()
agn_nm_le.fit(train['agency_name'])
agn_nm_le.classes_

array(['Buildings, Safety Engineering & Env Department',
       'Department of Public Works', 'Detroit Police Department',
       'Health Department', 'Neighborhood City Halls'], dtype=object)

In [33]:
np.unique(agn_nm_le.transform(train['agency_name']))  # label encoder

array([0, 1, 2, 3, 4])

In [34]:
train['agency_label']=agn_nm_le.transform(train['agency_name'])

In [35]:
disp_le=LabelEncoder()
disp_le.fit(train['disposition'])
train['disp_label']=disp_le.transform(train['disposition'])

In [36]:
train.dtypes

agency_name         object
inspector_name      object
violation_code      object
disposition         object
fine_amount        float64
discount_amount    float64
lat                float64
lon                float64
compliance            bool
agency_label         int64
disp_label           int64
dtype: object

In [37]:
df=train.drop(labels=['inspector_name','agency_name','violation_code','disposition'],axis=1)

In [38]:
df['agency_label']=df['agency_label'].astype('category')
df['disp_label']=df['disp_label'].astype('category')

In [39]:
df.dtypes

fine_amount         float64
discount_amount     float64
lat                 float64
lon                 float64
compliance             bool
agency_label       category
disp_label         category
dtype: object

In [40]:
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score

In [41]:
#X,y=df.drop(labels=['compliance','disp_label'],axis=1),df['compliance']
X,y=df.drop(labels=['compliance'],axis=1),df['compliance']

In [42]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,train_size=0.8)

In [43]:
from sklearn.ensemble import RandomForestClassifier

clf=RandomForestClassifier(n_estimators=30,random_state=0)#.fit(X_train,y_train)

In [44]:
print('Cross-validation (AUC)',cross_val_score(clf,X_train,y_train,cv=5,scoring='roc_auc'))

Cross-validation (AUC) [ 0.77428557  0.77043537  0.77611169  0.78293839  0.77488133]


In [45]:
print('Cross-validation (AUC)',cross_val_score(clf,X_train,y_train,cv=5,scoring='roc_auc'))

Cross-validation (AUC) [ 0.77428557  0.77043537  0.77611169  0.78293839  0.77488133]


In [46]:
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=30, n_jobs=1, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [47]:
clf.score(X_train,y_train)

0.98903066410220319

In [48]:
clf.score(X_test,y_test)

0.92957217913435075

In [50]:
from sklearn.metrics import roc_curve,auc
y_proba_lr=clf.fit(X_train,y_train).predict_proba(X_test)
fpr_lr,tpr_lr,_=roc_curve(y_test,y_proba_lr[:,1])
roc_auc_lr=auc(fpr_lr,tpr_lr)
print(roc_auc_lr)

0.780387260396


In [51]:
y_proba_lr[:,1]

array([ 0.1       ,  0.        ,  0.        , ...,  0.        ,
        0.03333333,  0.        ])

In [52]:
from sklearn.metrics import confusion_matrix,classification_report

In [54]:
confusion_matrix(y_test,y_proba_lr[:,1]>=0.5)

array([[28994,   629],
       [ 1664,   689]])

In [55]:
print(classification_report(y_test,y_proba_lr[:,1]>=0.5))

             precision    recall  f1-score   support

      False       0.95      0.98      0.96     29623
       True       0.52      0.29      0.38      2353

avg / total       0.91      0.93      0.92     31976



In [56]:
test=test[['agency_name', 'disposition', 'fine_amount','discount_amount','lat', 'lon','address']]

In [57]:
test['agency_label']=agn_nm_le.transform(test['agency_name'])
#test['disp_label']=disp_le.transform(test['disposition'])

In [58]:
def chg_disp(x):
    if x =='Responsible (Fine Waived) by Admis':
        result='Responsible by Admission'
    elif x=='Responsible - Compl/Adj by Default':
        result='Responsible by Default'
    elif x=='Responsible - Compl/Adj by Determi':
        result='Responsible by Determination'
    elif x=='Responsible by Dismissal':
        result='Responsible by Default'
    else:
        result=x
    return result

In [59]:
test['disposition_new']=test['disposition'].apply(lambda x:chg_disp(x))

In [60]:
train['disposition'].unique()

array(['Responsible by Default', 'Responsible by Determination',
       'Responsible by Admission', 'Responsible (Fine Waived) by Deter'], dtype=object)

In [61]:
test['disposition'].unique()

array(['Responsible by Default', 'Responsible by Determination',
       'Responsible by Admission', 'Responsible (Fine Waived) by Deter',
       'Responsible (Fine Waived) by Admis',
       'Responsible - Compl/Adj by Default',
       'Responsible - Compl/Adj by Determi', 'Responsible by Dismissal'], dtype=object)

In [62]:
test['disposition'].value_counts()

Responsible by Default                51602
Responsible by Admission               4484
Responsible by Determination           4124
Responsible (Fine Waived) by Deter      781
Responsible - Compl/Adj by Default        6
Responsible - Compl/Adj by Determi        2
Responsible by Dismissal                  1
Responsible (Fine Waived) by Admis        1
Name: disposition, dtype: int64

In [63]:
test['disposition_new'].value_counts()

Responsible by Default                51609
Responsible by Admission               4485
Responsible by Determination           4126
Responsible (Fine Waived) by Deter      781
Name: disposition_new, dtype: int64

In [64]:
test['disp_label']=disp_le.transform(test['disposition_new'])

In [65]:
test.drop(labels=['agency_name','disposition','disposition_new'],axis=1,inplace=True)

In [66]:
test.head()

fine_amount  discount_amount        lat        lon  \
0        200.0              0.0  42.407581 -82.986642   
1       1000.0              0.0  42.426239 -83.238259   
2        100.0              0.0  42.426239 -83.238259   
3        200.0              0.0  42.309661 -83.122426   
4        100.0              0.0  42.308830 -83.121116   

                       address  agency_label  disp_label  
0  10041 roseberry, Detroit MI             1           2  
1  18520 evergreen, Detroit MI             1           2  
2  18520 evergreen, Detroit MI             1           2  
3     1835 central, Detroit MI             1           2  
4     1700 central, Detroit MI             1           2

In [67]:
X.head()

fine_amount  discount_amount        lat        lon agency_label disp_label
0        250.0              0.0  42.390729 -83.124268            0          2
1        750.0              0.0  42.326937 -83.135118            0          3
5        250.0              0.0  42.145257 -83.208233            0          2
6        750.0              0.0  42.433466 -83.023493            0          2
7        100.0              0.0  42.388641 -83.037858            0          2

In [68]:
test.apply(lambda x:sum(x.isnull()))

fine_amount        0
discount_amount    0
lat                5
lon                5
address            0
agency_label       0
disp_label         0
dtype: int64

In [89]:
test[test['lat'].isnull()]

Empty DataFrame
Columns: [fine_amount, discount_amount, lat, lon, address, agency_label, disp_label]
Index: []

In [81]:
'ABD'.lower()

'abd'

In [87]:
ll[ll['address'].str.contains('6200 16th st')].sort_values(by='address').head(20)

address        lat        lon
19737        6200 16th st, Detroit MI  42.359923 -83.095686
17293  6200 16th st, Detroit MI 482O8        NaN        NaN

In [88]:
## fixing the lat and lon missing values by looking up the average values in the nearby address
test.loc[20459,'lat']=(42.446417+42.446670)/2
test.loc[20459,'lon']=(-83.023725-83.023182)/2

test.loc[28350,'lat']=42.358858
test.loc[28350,'lon']=-83.151228

test.loc[28416,'lat']=42.358530
test.loc[28416,'lon']=-83.080371

test.loc[31925,'lat']=42.376722
test.loc[31925,'lon']=-83.143074

test.loc[55400,'lat']=42.359923
test.loc[55400,'lon']=-83.095686


In [79]:
test.iloc[20459]

fine_amount                               500
discount_amount                             0
lat                                   42.4465
lon                                  -83.0235
address            20424 bramford, Detroit MI
agency_label                                2
disp_label                                  2
Name: 20459, dtype: object

In [91]:
test.drop(labels='address',axis=1,inplace=True)

In [92]:
test.head()

fine_amount  discount_amount        lat        lon  agency_label  \
0        200.0              0.0  42.407581 -82.986642             1   
1       1000.0              0.0  42.426239 -83.238259             1   
2        100.0              0.0  42.426239 -83.238259             1   
3        200.0              0.0  42.309661 -83.122426             1   
4        100.0              0.0  42.308830 -83.121116             1   

   disp_label  
0           2  
1           2  
2           2  
3           2  
4           2

In [93]:
train.head()

agency_name    inspector_name  \
0  Buildings, Safety Engineering & Env Department   Sims, Martinzie   
1  Buildings, Safety Engineering & Env Department  Williams, Darrin   
5  Buildings, Safety Engineering & Env Department   Sims, Martinzie   
6  Buildings, Safety Engineering & Env Department  Williams, Darrin   
7  Buildings, Safety Engineering & Env Department  Williams, Darrin   

  violation_code                   disposition  fine_amount  discount_amount  \
0      9-1-36(a)        Responsible by Default        250.0              0.0   
1     61-63.0600  Responsible by Determination        750.0              0.0   
5      9-1-36(a)        Responsible by Default        250.0              0.0   
6     61-63.0500        Responsible by Default        750.0              0.0   
7     61-63.0100        Responsible by Default        100.0              0.0   

         lat        lon compliance  agency_label  disp_label  
0  42.390729 -83.124268      False             0           2  
1  42.326937 -83.135118       True             0           3  
5  42.145257 -83.208233      False             0           2  
6  42.433466 -83.023493      False             0           2  
7  42.388641 -83.037858      False             0           2

In [94]:
y_pred=clf.predict_proba(test)

In [96]:
y_pred_proba=y_pred[:,1]

In [97]:
y_pred_proba[:10]

array([ 0.        ,  0.        ,  0.        ,  0.06666667,  0.        ,
        0.16666667,  0.06666667,  0.96666667,  0.12222222,  0.        ])